# 									
# Decays of U238 in analog MC mode   
#
#                                                                         
/control/verbose 2
/run/verbose 1
#
/run/initialize
#
/process/list
#
# rdm is applied only to the different soil layers
/process/had/rdm/noVolumes
/process/had/rdm/selectVolume shellLV_1
/process/had/rdm/selectVolume shellLV_2
/process/had/rdm/selectVolume shellLV_3
/process/had/rdm/selectVolume shellLV_4
/process/had/rdm/selectVolume shellLV_5
# /process/had/rdm/selectVolume World
#
#
#
# place the isotopes in the middle of the target, at rest. 
#
/gun/particle ion
/gun/ion 86 222
#/gun/direction 0.3 0.5 0.3
#/gun/energy 15 MeV
#
#
#
#/vis/viewer/set/style surface
#/vis/viewer/addCutawayPlane 0 1 0 
#/vis/viewer/set/background white
/run/printProgress 100
/run/beamOn 100
