# 									
# Decays of U238 in analog MC mode   
#
#                                                                         
/control/verbose 2
/run/verbose 1
#
/run/initialize
#
/process/list
#
# rdm is applied only to the different soil layers
/process/had/rdm/noVolumes
/process/had/rdm/selectVolume shellLV
/process/had/rdm/selectVolume shellLV_1
/process/had/rdm/selectVolume shellLV_2
/process/had/rdm/selectVolume shellLV_3
/process/had/rdm/selectVolume shellLV_4
# /process/had/rdm/selectVolume World
#
#
#
# place the isotopes in the middle of the target, at rest. 
#
/gun/particle ion
/gun/ion 92 238
#
#
# run 1
/analysis/setFileName output_param_pH_4
/run/printProgress 100
/nb/det/pH/setH 4
/run/beamOn 1000
#
# run 2
/analysis/setFileName output_param_pH_45
/run/printProgress 100
/nb/det/pH/setH 4.5
/run/beamOn 1000
#

# run 3
/analysis/setFileName output_param_pH_5
/run/printProgress 100
/nb/det/pH/setH 5
/run/beamOn 1000
#
# run 4
/analysis/setFileName output_param_pH_55
/run/printProgress 100
/nb/det/pH/setH 5.5
/run/beamOn 1000
#
# run 5
/analysis/setFileName output_param_pH_6
/run/printProgress 100
/nb/det/pH/setH 6
/run/beamOn 1000
#
# run 6
/analysis/setFileName output_param_pH_65
/run/printProgress 100
/nb/det/pH/setH 6.5
/run/beamOn 1000
#
# run 7
/analysis/setFileName output_param_pH_7
/run/printProgress 100
/nb/det/pH/setH 7
/run/beamOn 1000
#
# run 8
/analysis/setFileName output_param_pH_75
/run/printProgress 100
/nb/det/pH/setH 7.5
/run/beamOn 1000
#
# run 9
/analysis/setFileName output_param_pH_8
/run/printProgress 100
/nb/det/pH/setH 8
/run/beamOn 1000
#
/control/shell rm main_pH_root_file
#
/control/shell hadd main_pH_root_file output_param_pH_4.root output_param_pH_45.root output_param_pH_5.root output_param_pH_55.root output_param_pH_6.root output_param_pH_65.root output_param_pH_7.root output_param_pH_75.root output_param_pH_8.root
